### ISSUE TITLE
Reliable FLRC

### ISSUE THREAD

**Issue by ArduinoShop** [StuartsProjects/SX1280_Testing#2]
Hi, Stuart - you come highly recommended by Andreas..

I have been using your fine library with SemTech SX1280 modules - your examples work fantastic!!!

My project requires the Reliable ACK with data which I have working great in LoRa Mode..

The reason for raising this Issue is that when I change the ___setup to LT.setupFLRC(Fr...

I get no ACKs back to the Transmitter...

Any comments on this matter - Am I trying to do something that cannot be done?...

**Comment by StuartsProjects** [comment]
I dont recall if you raised this issue in the actual library Github, but issues with FLRC can occur if you dont set the FLRC packet length to stay within 127 bytes, including header. 

This SX1280_Testing Github is shortly to be deleted. All the reports are in the blog.
