### ISSUE TITLE
Request for Code

### ISSUE THREAD

**Issue by ElectronicallyE** [StuartsProjects/SX1280_Testing#3]
Hi Stuart,

I've had a read of your project, very interesting indeed. I would like to try this myself, but it does not appear that the code has been uploaded.

> Semtech produce a development kit with sample code but it was not in a format that allowed for its use in the Arduino environment. The class based structure of the original bits of code was removed and reduced to just two code files, SX1280Library.h and SX1280Includes.h for Arduino. These bits of code currently just need to be included in the same folder\directory as the Arduino .ino file. When I am fully happy with the code it will be published.

Are you happy enough for the code to be uploaded now? If it is in a developmental state, can you please let me know what errors/issues are unresolved?

Furthermore, do you have a link to the sample code which you based your code upon?

Kind regards,

Lachlan

**Comment by ElectronicallyE** [comment]
After some searching, I have come across this library of yours:
[https://github.com/StuartsProjects/SX12XX-LoRa](https://github.com/StuartsProjects/SX12XX-LoRa)

Just to be sure, can you confirm this contains the code to test the ranging engine/time-of-flight function?

**Comment by StuartsProjects** [comment]
Yes the SX12XX-LoRa library contains the ranging examples and calibration program. 

This GITHUB is redundant, the code\examples are in the library and the testing reports etc are on the blog, so I will delete this GITHUB soon.
